### ISSUE TITLE
Моё честно мнение - Ты чего наделал???

### ISSUE THREAD

**Issue by EgrShishov** [Rosto4eks/StathamFilms#1]
- Стэтхем филмс? А почему не гослингс? Странное решени
- Сортировка фильмов по различным параметрам (дата добавления, рейтинг, **популярность**) не считаю, что фильмы со стейтемом должны так сортироваться, они все популярны (Вспомни пчеловода)
- Отображение детальной информации о фильме (описание, **актерский состав**, режиссер, год выпуска, рейтинг) актерский состав лишнее, все и так знают, что там только стейтем
- Система оценок фильмов (например, **от 1 до 10 звезд**) должно быть только 10 звезд
- **CRUD операции с пользователями, актерами, режиссерами**, отзывами, фильмами и категориями надеюсь со стейтемом ничего не наделаешь
- **Журналирование** Сохранение истории подписок и просмотренных фильмов пользователя. звучит как название какой-то стрижки, убрать

**Comment by Rosto4eks** [comment]
нет
